version: '3'
services:
  web:
    build: ./nginx
    ports:
      - "80:80"
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access

  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    build: ./elasticsearch
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    build: ./kibana
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
